l_english:
 SETTING_REFRACTION: "Рефракція"
 SETTING_REFRACTION_QUALITY: "Якість рефракції"
 SETTING_MAPOBJECT_QUALITY: "Об'єкти карти"
 SETTING_MAP_SSAO: "SSAO карти"
 SETTING_DOF: "Глибина різкості"
 SETTING_LENS_FLARE: "Відблиски лінз"
 SETTING_SECONDARY_LENS_FLARE: "Вторинні відблиски лінз"
